config/routes.rb
Rails.application.routes.draw do

  resources :orders, only: [:new, :create] do
    collection do
      get 'cancel' => 'orders#cancel'
      get 'express_checkout' => 'orders#express_checkout' 
      get 'make_orders'=> 'orders#make_orders'
      get 'failure' => 'orders#failure'
      get 'successful' => 'orders#successful'
    end
  end
    

  root 'orders#make_orders'

end

app/models/order.rb
class Order < ActiveRecord::Base
  def purchase
    response = EXPRESS_GATEWAY.purchase(150, express_purchase_options)
    self.update_attribute(:purchased_at, Time.now) if response.success?
    response.success?
  end

  def express_token=(token)
    self[:express_token] = token
    if new_record? && !token.blank?
      # you can dump details var if you need more info from buyer
      details = EXPRESS_GATEWAY.details_for(token)
      self.express_payer_id = details.payer_id
    end
  end

  private

  def express_purchase_options
    {
      :ip => ip,
      :token => express_token,
      :payer_id => express_payer_id
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
     @order = Order.new(:express_token => params[:token])
  end

  def create
    @order = Order.new(order_params)
    @order.ip = request.remote_ip
  
    if @order.save
      if @order.purchase # this is where we purchase the order. refer to the model method below
        redirect_to successful_orders_url(@order)
      else
        render :action => "failure"
      end
    else
      render :action => 'new'
    end    
  end

  def express_checkout
     response = ::EXPRESS_GATEWAY.setup_purchase(150,
      ip: request.remote_ip,
      return_url: new_order_url,
      cancel_return_url: cancel_orders_url,
      currency: "USD",
      allow_guest_checkout: true,
      items: [{name: "Order", description: "Order description", quantity: "1", amount: 150}]
    )
    redirect_to ::EXPRESS_GATEWAY.redirect_url_for(response.token)
  end
  
  def failure
  end
  
  def make_orders
  end
  
  def cancel
  end
  
  def successful_orders
  end
  
  def order_params
    params.require(:order).permit(:ip, :express_token, :exxpress_payer_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/cancel.html.erb
<h1>Cancel Order</h1>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/express_checkout.html.erb
<h1>Orders#express_checkout</h1>
<p>Find me in app/views/orders/express_checkout.html.erb</p>

app/views/orders/make_orders.html.erb
<h1>Make Paypal Express Payment</h1>
<br/>

<%= link_to(image_tag("https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), express_checkout_orders_path) %>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

<%= @order.inspect %>

<%= @order.errors.full_messages %>

<%= form_for @order do |f| %>
  
  <% if @order.express_token.blank? %>
    Something went wrong. Check with the Admins.
  <% else %>
    <%= f.hidden_field :express_token %>
    <p>About to complete order for $1.50.</p>
    <p>TODO Display order confirmation details</p>
  <% end %>
  <p><%= f.submit "Complete Order" %></p>
<% end %>